import { link } from 'fs'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links=[
  {
    href:'/',label:'home'
  },
  {
    href:'/docs',label:'Docs'
  },
  {
    href:'/todos',label:'Todos'
  }
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className='flex items-center'>
              {links.map(link=>(
                <li>
                  <Link href={link.href}>{link.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
      <div>
        {children}
      </div>
      </body>
    </html>
  )
}
